### ISSUE TITLE
Build Dependencies not loading

### ISSUE THREAD

**Issue by jpc2350** [easybuilders/easybuild-framework#2318]
Hi Guys,

I'm struggling to get builddependencies to load into the build environment when building Automake-1.15.1

I've got the following in the easyconfig file:
builddependencies = [
    ('binutils', '2.28'),
    ('flex', '2.6.4'),
    ('Bison', '3.0.4')
]

dependencies = [
    ('Autoconf', '2.69'),
]

And I'm using 
`eb Automake-1.15.1.eb --robot` and 
`eb Automake-1.15.1.eb --robot --use-existing-modules`

neither of which load the build dependencies.

The EB build log produces this output:
checking for tex... tex
checking for yacc... no
checking for byacc... no
checking for bison... no
checking for lex... no
checking for flex... no
checking whether autoconf is installed... no
configure: error: Autoconf 2.65 or better is required.
    Please make sure it is installed and in your PATH.
 (at easybuild/tools/run.py:469 in parse_cmd_output)
== 2017-09-29 14:55:46,683 easyblock.py:2650 WARNING build failed (first 300 chars): cmd " ./configure --prefix=/tools/ebpoc/apps/Automake/1.15.1 " exited with exitcode 1 and output:
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bi
== 2017-09-29 14:55:46,683 easyblock.py:287 INFO Closing log for application name Automake version 1.15.1

The [config.log](https://github.com/easybuilders/easybuild-framework/files/1344575/config.log) from Automake. As you can see the PATH for the all the dependencies don't appear in the PATH variable.

Any way I try and build it, it fails because it can't find those binaries in the PATH.

**Comment by boegel** [comment]
@jpc2350 This probably happens because you have `dummy` listed as `version` in the `toolchain` spec, just use an empty version (`''`) instead; see also http://easybuild.readthedocs.io/en/latest/Concepts_and_Terminology.html?#dummy-toolchain .

This is weird behaviour, it's a historical mistake, we hope to get rid of this when we 'rebrand' the `dummy` toolchain concept into the more meaningful `system` toolchain (see https://github.com/easybuilders/easybuild-framework/pull/1233).

**Comment by jpc2350** [comment]
Ahhhhh that makes sense now, changed and it's now working correctly! Thanks @boegel
