### ISSUE TITLE
make robot only require toolchain definitions to resolve dependencies with subtoolchains 

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#2375]
Currently, the `--robot` implementation will only resolve dependencies via a subtoolchain if the matching easyconfig file is available in the robot search path (even if the corresponding module is available already).

However, I don't think there's a strict need for it, it should suffice that just the easyconfigs that define the toolchain are available, since that's sufficient to figure out the subtoolchains to consider (w.r.t. versions).

Once the subtoolchains are known, available modules can be sufficient to resolve a dependency via a subtoolchain (unless there are other aspects that require the easyconfigs to be available, e.g. the use of `HierarchicalMNS` which requires an easyconfig file to determine the full module name).

Thoughts @ocaisa?

**Comment by ocaisa** [comment]
This approach also wouldn't work if `modaltsoftname` was used in the (now unparsed) dep easyconfig as the module name wouldn't be correct.

**Comment by paulmelis** [comment]
To clearify, is this bug applicable only when `--robot` is used?

**Comment by boegel** [comment]
@paulmelis Hmm, good question... It's actually the process of finding modules for each of the dependencies, which is not *exactly* the same as `--robot` (which does more than that).

@ocaisa I hope to find time to try and fix this bug soon. You've been doing quite a bit of work related to subtoolchains recently, any idea how difficult this would be?

**Comment by boegel** [comment]
I took a quick look at this, and it seems we can avoid the requirement that the easyconfig file for the dependencies are available via the robot search path by not always calling `robot_find_easyconfig` in `robot_find_minimal_toolchain_of_dependency`, which takes care of figuring out which subtoolchain should be used for each dependency.

There's a complication though... The alternative for considering subtoolchains is looking at existing modules to pick a subtoolchain for a particular dependency, which currently requires that `--use-existing-modules` is enabled (it's disabled by default).

Also, the problem reported in #2535 and the proposed fix in #2536 potentially complicates the situation even further...

@ocaisa I'd like to pick your brain on this one, can we set up a conf call on this sometime soon?

**Comment by casparvl** [comment]
+1, I have some new colleagues and it is hard to explain to them why this is happening (‘but… the module is already there!’). If EasyBuild can do without the EasyConfig, that would definitely be more intuitive behaviour :)

**Comment by akesandgren** [comment]
And you're not telling EB to use the ebfiles_repo to search for easyconfigs? If there is a module there should (normally) be an easyconfig in there that matches.

**Comment by boegel** [comment]
@akesandgren You can indeed circumvent the issue that way, but that's not the default configuration, and maybe people have good reasons not to do so...

**Comment by akesandgren** [comment]
Perhaps, but to me that's the way you need to do it if you are using --try-toolchain*/--try-software-version and some other cases (like building from develop directly without copying to your own repo)

**Comment by ocaisa** [comment]
There is another path: if the module exists then it sets `EBROOTXXX` in which you will always find `easybuild/XXX-YYY.eb` (or even `easybuild/reprod/XXX-YYY.eb`) so if we extract that envvar from the module we can always find the corresponding easyconfig without any ambiguity.

**Comment by ocaisa** [comment]
You could trigger building a list of these paths from the available modules when `--use-existing-modules` is set and then simply add that list to the easyconfig cache.

**Comment by boegel** [comment]
@ocaisa The thing is, we don't even need the easyconfig files at all (in a non-HMNS context) to determine which subtoolchains to consider, so we shouldn't be enforcing that.

Just having the full toolchain definition (we do need easyconfigs for the toolchain itself) is sufficient to known which modules to check for.

What's not entirely clear to me yet is how `--use-existing-modules` comes into play here: should that really only be relevant when `--minimal-toolchains` is enabled, since we're also considering subtoolchains by default (just in a different direction)?

**Comment by ocaisa** [comment]
> Just having the full toolchain definition (we do need easyconfigs for the toolchain itself) is sufficient to known which modules to check for.

This is not strictly true, if an easyconfig uses `modaltsoftname` then this guess will not be correct, even with a flat MNS...but this was already an issue with dependency resolution: https://github.com/easybuilders/easybuild-framework/issues/1556

In general I'm not sure you're coming at it right by saying you don't need the easyconfigs "in a non-HMNS context" when what you actually mean is that you don't need them in a flat naming scheme...but that is not _necessarily_ true in any other MNS (and we don't know how many are out there).

Having said that, you could offer up a fix for the current default MNS here. If you want to avoid calls to `robot_find_minimal_toolchain_of_dependency`, then `--use-existing-modules` has more scope now and should perhaps be set to default to yes in the case where you are not using minimal toolchains but false if you are (to preserve current behaviour). You make the list of modules to check for, check their availability and use the highest toolchain in the list that comes back. In this case, whether or not you have minimal toolchains is irrelevant because you actually want the highest toolchain in both cases (the specific case `--use-existing-modules` was created for was `zlib` where you want to use the Intel compiled version over the `GCCcore` version if it's available).

**Comment by boegel** [comment]
fixed in #2690
