### ISSUE TITLE
--from-pr does not seem to merge with develop branch

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-framework#2496]
While testing https://github.com/easybuilders/easybuild-easyconfigs/pull/6263 with `--from-pr`, it seems that a previously merged PR (https://github.com/easybuilders/easybuild-easyconfigs/pull/6261) does not get pulled automatically.

Full debug log:
https://gist.github.com/vanzod/a19c284ce3dd953a886b72cfcec2aecc

**Comment by boegel** [comment]
@vanzod `eb` *does* merge the PR with `develop` before actually using the easyconfigs, that's not the problem:

```
== 2018-05-02 09:46:51,209 run.py:508 DEBUG cmd "tar xzf /tmp/eb-fbyUr0/tmpVxHShw/easybuilders/develop.tar.gz" exited with exit code 0 and output:
...
== 2018-05-02 09:46:52,530 run.py:508 DEBUG cmd "patch -b -p1 -i /tmp/eb-fbyUr0/tmpVxHShw/easybuilders/easybuild-easyconfigs-develop/6263.diff" exited with exit code 0 and output:
patching file easybuild/easyconfigs/l/lxml/lxml-4.2.0-intel-2018a-Python-3.6.4.eb
patching file easybuild/easyconfigs/n/Nipype/Nipype-1.0.2-intel-2018a-Python-3.6.4.eb
...
```

The problem is that you have `/opt/easybuild/ebfiles_repo` listed in `--robot-paths`, and that the easyconfig for the `NiBabel` dependency is taken from there:

```
== 2018-05-02 09:46:55,463 easyconfig.py:1257 DEBUG Processing easyconfig /opt/easybuild/ebfiles_repo/NiBabel/NiBabel-2.2.1-intel-2018a-Python-3.6.4.eb
```

This easyconfig was installed with a version of framework that pre-dates https://github.com/easybuilders/easybuild-framework/pull/2493, and sets `download_dep_fail`, but that was a mistake (cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/6261).

It `/opt/easybuild/ebfiles_repo` would not be in the robot search path, `eb` would have found the `NiBabel` easyconfig in `/tmp/eb-fbyUr0/tmpVxHShw/easybuilders/easybuild-easyconfigs-develop`, and then it would have used the corrected one...

**Comment by vanzod** [comment]
Correct. I removed the file and it proceeded correctly.
Closing issue.
