### ISSUE TITLE
Checksums are not enforced for Perl exts

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-framework#2550]
When building a Perl bundle checksums are not enforced for the single extensions even if `enforce-checksums = true`.
The issue may extend to other type of bundles too.

**Comment by boegel** [comment]
Hmm, that's a bit strange, since the only place whether we're checking if `--enforce-checksums` is set is in `verify_checksum`, which should be called for all sources & patches, regardless of whether they're for extensions or not, see https://github.com/easybuilders/easybuild-framework/blob/c76c5e94375f9a17b822b622ed9d7b6d175f3bd8/easybuild/tools/filetools.py#L675 ...

**Comment by boegel** [comment]
@vanzod After staring at this for a while, I suddenly realized what the problem was: the `if checksums:` guard in `fetch_extension_sources` which effectively skips the call to `verify_checksum`... :-/

Fix in #2561
