### ISSUE TITLE
Allow for extract_step to be overridden in general

### ISSUE THREAD

**Issue by rjeschmi** [easybuilders/easybuild-framework#2612]
It was pointed out on IRC that it would be nice to pick files from sources without extraction and to run MakeCp against them

It seems like perhaps a general option could be added to EasyBlock to skip that, but no other options exist like that:
https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L113

Is there a reason why? Would this be similar to a working with a different extract step (like a git clone or something?)

**Comment by fgeorgatos** [comment]
interesting... example case? `hello.c` ? if it is what i understand, you could hack the tar extraction...

**Comment by rjeschmi** [comment]
yeah, like that from a remote url. I don't think we need to do anything fancy if it works with binary now.

**Comment by boegel** [comment]
We already support this basically, you can specify custom extraction commands via `extract_cmd` (like `cp`), see https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#alternative-formats-for-sources .

For the `Binary` easyblock (and anything derived from it), we have a dedicated `extract_sources` easyconfig parameter because with `Binary` the default is to *not* unpack, since it's intended for (non-packaged) binary installers.

**Comment by rjeschmi** [comment]
This is great, thanks. Let me digest this a bit, but hopefully the original reporter sees this and it helps solve his problem.

Providing an extract_cmd of empty will do what he wanted, that is probably satisfactory.

I'll just close this then?

**Comment by boegel** [comment]
@rjeschmi Well, the `extract_cmd` can't be *empty*, but it can do a simple `cp` rather than untarring/unzipping, for example:

```python
sources = [{'filename': 'example.c', 'extract_cmd': "cp %s %(builddir)s"}]
```

I think this issue can be closed...

**Comment by akesandgren** [comment]
You can make an "empty" on by doing "true %s" or similar, if that's what you need.
