### ISSUE TITLE
Modules: Set CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by ax3l** [easybuilders/easybuild-framework#2624]
Hi,

I am a user of several HPC systems that use Easybuild as a package manager (CSCS, TU Dresden). As a power-user and heavy developer, we use package software from modules on HPC systems to develop and build further software - outside of those package managers.

In the case of our software stack, we heavily rely on CMake and for such we would like to set the `CMAKE_PREFIX_PATH` when loading modules automatically to the prefix of installed software. The CMake build system heavily relies on those to find software of any kind (and prefer it over e.g. system paths).

How can one generally *configure* Easybuild to *always* prepend `CMAKE_PREFIX_PATH` in modules?
Should one introduce a more general templating mechanism for modules outside of [`--modules-footer`](https://easybuild.readthedocs.io/en/latest/version-specific/help.html)?

As a heavy [Spack](http://spack.io/) user myself, I am quite in love with the module configuration I can use there and therefore I am quite biased :) Maybe that's useful for Easybuild as well?
https://spack.readthedocs.io/en/latest/module_file_support.html#write-a-configuration-file

**Comment by ocaisa** [comment]
Hmm, I'd say people probably have some opinions on this. If you want a quick fix for now, you can just leverage the `$EBROOT*` variables that are set for every EB module:
```
export CMAKE_PREFIX_PATH=$(env | grep EBROOT | sed  s/=/\ /|awk '{print $2}'|tr '\n' ':')$CMAKE_PREFIX_PATH
```

**Comment by ocaisa** [comment]
Having configurable modules has been discussed before but noone has gotten around to an implementation.

**Comment by boegel** [comment]
The idea of having a default module file template that you can customize has indeed been discussed before.

It shouldn't be terribly hard to implement either, I think it's mostly because of a lack of time and the fact that nobody has had a strong use case for it yet...

To make it concrete: someone implementing this would have to dive into `easybuild/framework/easyblock.py` and make `make_module_step` use a template of a module file rather than concatenating a set of strings obtained by calling the different `make_module*` methods.

**Comment by boegel** [comment]
First stab at adding support for using a custom module file template in #2639 .

For @ax3l's use case, `--modules-footer` is still a good option though:

```
$ cat $HOME/my-modules-footer.lua
prepend_path("CMAKE_PREFIX_PATH", "%(installdir)s")
```

```
$ eb --modules-footer $HOME/my-modules-footer.lua ...

# or

$ export EASYBUILD_MODULES_FOOTER=$HOME/my-modules-footer.lua
$ eb ...
```

**Comment by Flamefire** [comment]
This is getting old now. How about adding `prepend_path("CMAKE_PREFIX_PATH", "%(installdir)s")` to the default EB?

**Comment by ocaisa** [comment]
There are actually now two solutions to this issue, the one from @boegel above and a more general one using [hooks](https://easybuild.readthedocs.io/en/latest/Hooks.html).
I probably agree that this is a good idea (@akesandgren is, I think, more familiar with CMake than me) but it potentially has a big impact on users. Even if we thought it was a good idea to force this, it could have enough of an impact that we would have to default it off until the next major release.

**Comment by ocaisa** [comment]
This actually came up (more or less) in the [confcall on Wednesday](https://github.com/easybuilders/easybuild/wiki/Conference-call-notes-20191211).

**Comment by akesandgren** [comment]
For EB itself this shouldn't be a problem. We already set CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH in the cmakemake.py easyblock to the combined list of the toolchain includes and libdirs.
CMAKE_PREFIX_PATH is just another variable it will use to do the same things as the other two.

The caveat here is that CMAKE_PREFIX_PATH looks in <prefix>/lib/<arch> if CMAKE_LIBRARY_ARCHITECTURE is set and in <prefix>/lib otherwise.
Not all libs are installed in <prefix>/lib, on some systems they end up in <prefix>/lib64, so we would still have to set CMAKE_LIBRARY_PATH.

We could also make sure to set CMAKE_PROGRAM_PATH to point to the [s]bin dir of installed software. but CMAKE_PREFIX_PATH is already used to look in <prefix>/[s]bin.

So, for most, but not all, packages setting CMAKE_PREFIX_PATH to $EBROOTXXX is usually enough. Also setting CMAKE_LIBRARY_PATH to the actual libdir would be required.

So, from a user perspective (not using EB itself that is) having them set is likely a good idea.

(Unfortunately, too many cmake based codes are using NO_DEFAULT_PATH when doing find_xxx which makes all this useless)

**Comment by Flamefire** [comment]
> The caveat here is that CMAKE_PREFIX_PATH looks in `/lib/<arch>` if CMAKE_LIBRARY_ARCHITECTURE is set and in /lib otherwise.

No, you misunderstood the docs. There is no **otherwise**, it looks in `/lib/<arch>` before `/lib` if the arch is set. (Otherwise it just looks in the second) See https://cmake.org/cmake/help/latest/command/find_library.html

> So, for most, but not all, packages setting CMAKE_PREFIX_PATH to $EBROOTXXX is usually enough. Also setting CMAKE_LIBRARY_PATH to the actual libdir would be required.

IMO `CMAKE_PREFIX_PATH` is enough, `CMAKE_LIBRARY_PATH` is not required.

> So, from a user perspective (not using EB itself that is) having them set is likely a good idea.

Very much so!

> (Unfortunately, too many cmake based codes are using NO_DEFAULT_PATH when doing find_xxx which makes all this useless)

Well, make it painful to use stuff "wrong". This may lead to better codes in the future. Nothing wrong with `NO_DEFAULT_PATH` if that find call is followed by another without though.

**Comment by akesandgren** [comment]
Yeah, sorry didn't mean to write otherwise. But it does not look in lib64 ever, which is where, on some distros, the libraries will be installed. Thus we need CMAKE_LIBRARY_PATH too.

**Comment by akesandgren** [comment]
Yeah, sorry didn't mean to write otherwise. But it does not look in lib64 ever, which is where, on some distros, the libraries will be installed. Thus we need CMAKE_LIBRARY_PATH too.

Unless FIND_LIBRARY_USE_LIB64_PATHS is set... missed that one (again)

However I don't know if it looks in both lib and lib64 if that is set or only in lib64.

It's still safer to set CMAKE_LIBRARY_PATH too.

**Comment by Flamefire** [comment]
> But it does not look in lib64 ever, which is where, on some distros, the libraries will be installed. Thus we need CMAKE_LIBRARY_PATH too.

Can you provide an example? Because I'd expect `CMAKE_LIBRARY_ARCHITECTURE` to be set on such distros: https://cmake.org/cmake/help/v3.4/variable/CMAKE_LIBRARY_ARCHITECTURE.html -> https://cmake.org/cmake/help/v3.4/variable/CMAKE_LANG_LIBRARY_ARCHITECTURE.html

```
Target architecture library directory name detected for <LANG>.

 If the <LANG> compiler passes to the linker an architecture-specific system library search directory such as <prefix>/lib/<arch> this variable contains the <arch> name if/as detected by CMake.
```

**Comment by akesandgren** [comment]
On our Ubuntu Xenial, some packages put stuff in lib64 and some in lib. This has nothing to do with CMake or the OS distro as such. 

For instance binary packages like cuDNN only have lib64 while most stuff is in lib.

**Comment by Flamefire** [comment]
Just seen that `CMAKE_LIBRARY_ARCHITECTURE` is unrelated. It appends a path, not change lib->lib64

Just checked CMake sources. It does set FIND_LIBRARY_USE_LIB64_PATHS by default: https://github.com/Kitware/CMake/blob/7574e16096abe57d44cde4e6380a22d940cde98c/Modules/Platform/UnixPaths.cmake#L91 but disabled for debians: https://github.com/Kitware/CMake/blob/7574e16096abe57d44cde4e6380a22d940cde98c/Modules/Platform/Linux.cmake#L58 with a comment `Debian has lib32 and lib64 paths only for compatibility so they should not be searched.`. So those package structures could probably be considered wrong. But well, you are right.

Then I'd say: prepend the lib64 path for a module if it exists, else dont touch `CMAKE_LIBRARY_PATH` to keep the impact minimal.

**Comment by akesandgren** [comment]
Yeah, that's what I had in mind above.

**Comment by boegel** [comment]
So who's up for translating this in a PR that also updates `$CMAKE_PREFIX_PATH` (+ `$CMAKE_LIBRARY_PATH` if needed)?

**Comment by Flamefire** [comment]
Done: #3176
