### ISSUE TITLE
problem with zlib dependency and module auto swap

### ISSUE THREAD

**Issue by pescobar** [easybuilders/easybuild-framework#2634]
I am using `EasyBuild/3.7.0` with `Lmod/7.4.5` and `LMOD_DISABLE_SAME_NAME_AUTOSWAP=yes`

When I try to install [Boost-1.61.0-foss-2016b.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/b/Boost/Boost-1.61.0-foss-2016b.eb) I am getting this error:

```
$> eb Boost-1.61.0-foss-2016b.eb --hide-deps=zlib,bzip2 -f

module load zlib/.1.2.8-GCCcore-5.4.0' failed with exit code 1; stderr: Lmod has detected the following error: The sciCORE cluster prevents the automatic swapping of modules with same name
```

In my cluster I have all these modules already installed:

```
foss/2016b
zlib/.1.2.8-foss-2016b
zlib/.1.2.8-GCCcore-5.4.0
```

@boegel mentioned in the chat that the issue could be related to this PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/6633

**Comment by pescobar** [comment]
I have uploaded a debug log here https://gist.github.com/e30a3db73bf0073255b96bc8efcdd2d0

**Comment by vanzod** [comment]
I agree with @boegel's diagnosis. With a flat naming scheme and `LMOD_DISABLE_SAME_NAME_AUTOSWAP=yes` the only solution I can see is to remove the `zlib/.1.2.8-GCCcore-5.4.0` and correct the modules dependency. With a HNMS it would be way easier to fix.

**Comment by pescobar** [comment]
@boegel this is the output of `eb -D`

```
$  eb Boost-1.61.0-foss-2016b.eb --hide-deps=zlib,bzip2 -f -D
== temporary log file in case of crash /scratch/eb-DKsHHB/easybuild-hub6zo.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/scicore/soft/apps/EasyBuild/3.7.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.7.0-py2.7.egg/easybuild/easyconfigs
 * [x] $CFGS/m/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [x] $CFGS/b/Bison/Bison-3.0.4.eb (module: Bison/3.0.4)
 * [ ] $CFGS/f/flex/flex-2.6.0.eb (module: flex/2.6.0)
 * [x] $CFGS/z/zlib/zlib-1.2.8.eb (module: zlib/.1.2.8)
 * [ ] $CFGS/b/binutils/binutils-2.26.eb (module: binutils/2.26)
 * [x] $CFGS/g/GCCcore/GCCcore-5.4.0.eb (module: GCCcore/5.4.0)
 * [x] $CFGS/z/zlib/zlib-1.2.8-GCCcore-5.4.0.eb (module: zlib/.1.2.8-GCCcore-5.4.0)
 * [ ] $CFGS/m/M4/M4-1.4.17-GCCcore-5.4.0.eb (module: M4/1.4.17-GCCcore-5.4.0)
 * [ ] $CFGS/b/Bison/Bison-3.0.4-GCCcore-5.4.0.eb (module: Bison/3.0.4-GCCcore-5.4.0)
 * [ ] $CFGS/f/flex/flex-2.6.0-GCCcore-5.4.0.eb (module: flex/2.6.0-GCCcore-5.4.0)
 * [ ] $CFGS/b/binutils/binutils-2.26-GCCcore-5.4.0.eb (module: binutils/2.26-GCCcore-5.4.0)
 * [x] $CFGS/g/GCC/GCC-5.4.0-2.26.eb (module: GCC/5.4.0-2.26)
 * [x] $CFGS/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1.eb (module: OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1)
 * [ ] $CFGS/m/M4/M4-1.4.17-GCC-5.4.0-2.26.eb (module: M4/1.4.17-GCC-5.4.0-2.26)
 * [ ] $CFGS/a/Autoconf/Autoconf-2.69-GCC-5.4.0-2.26.eb (module: Autoconf/2.69-GCC-5.4.0-2.26)
 * [ ] $CFGS/a/Automake/Automake-1.15-GCC-5.4.0-2.26.eb (module: Automake/1.15-GCC-5.4.0-2.26)
 * [ ] $CFGS/l/libtool/libtool-2.4.6-GCC-5.4.0-2.26.eb (module: libtool/2.4.6-GCC-5.4.0-2.26)
 * [ ] $CFGS/a/Autotools/Autotools-20150215-GCC-5.4.0-2.26.eb (module: Autotools/20150215-GCC-5.4.0-2.26)
 * [x] $CFGS/n/numactl/numactl-2.0.11-GCC-5.4.0-2.26.eb (module: numactl/2.0.11-GCC-5.4.0-2.26)
 * [x] $CFGS/h/hwloc/hwloc-1.11.3-GCC-5.4.0-2.26.eb (module: hwloc/1.11.3-GCC-5.4.0-2.26)
 * [x] $CFGS/o/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb (module: OpenMPI/1.10.3-GCC-5.4.0-2.26)
 * [x] $CFGS/g/gompi/gompi-2016b.eb (module: gompi/2016b)
 * [x] $CFGS/f/FFTW/FFTW-3.3.4-gompi-2016b.eb (module: FFTW/3.3.4-gompi-2016b)
 * [x] $CFGS/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1.eb (module: ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1)
 * [x] $CFGS/f/foss/foss-2016b.eb (module: foss/2016b)
 * [x] $CFGS/b/bzip2/bzip2-1.0.6-foss-2016b.eb (module: bzip2/.1.0.6-foss-2016b)
 * [F] $CFGS/b/Boost/Boost-1.61.0-foss-2016b.eb (module: Boost/1.61.0-foss-2016b)
== Temporary log file(s) /scratch/eb-DKsHHB/easybuild-hub6zo.log* have been removed.
== Temporary directory /scratch/eb-DKsHHB has been removed.
```

**Comment by boegel** [comment]
@pescobar The problem here is the `zlib/.1.2.8-foss-2016b` module you have...

It gets picked up to resolve the dependency for `Boost` (`eb` sees the module and is happy), but then it clashes with the `zlib/.1.2.8-GCCcore-5.4.0` that is used lower down the stack.
That's basically caused by the changes in https://github.com/easybuilders/easybuild-easyconfigs/pull/6633, where we (by exception) have made some backward-incompatible changes (by removing the `zlib-1.2.8-foss-2016b.eb` easyconfig & replacing it with `zlib-1.2.8-GCCcore-5.4.0.eb`).

The solution is to remove the `zlib/.1.2.8-foss-2016b` module, after you make very sure no other modules are loading this `zlib` module (hopefully a `grep` is sufficient for that in your setup).

If you do hit modules that load `zlib/.1.2.8-foss-2016b`, you should be able to search & replace with `zlib/.1.2.8-GCCcore-5.4.0` in those module files safely (the `zlib` installation is the same w.r.t. installed files, only the module name differs).

I'm really sorry about this mess, I clearly underestimated the potential impact of removing that easyconfig file. Lesson learned...

**Comment by pescobar** [comment]
thanks for the clarification. I have updated my existing modules so all them use `zlib-1.2.8-GCCcore-5.4.0.eb`
