### ISSUE TITLE
Architecture-specific dependencies

### ISSUE THREAD

**Issue by edmondac** [easybuilders/easybuild-framework#2655]
I propose adding an alternative way of specifying a dependency as a dict rather than a tuple. The dict should handle all the existing info from the tuple.

Then adding the ability to say which architecture it's for, like this:

To specify that mkl_dnn should only be included as a dep on x86_64:
```python
dependencies = [{'name': 'mkl_dnn', 'version': '0.16', 'arch': 'x86_64'}, ...]
```

To specify which Java should be used:
```python
dependencies = [
    {'name': 'Java', 'version': '%(version)s_191-b26-OpenJDK'', 'arch': 'ppc64le'},
    {'name': 'Java', 'version': '%(version)s.0_181', 'arch': 'x86_64'},
]
```

**Comment by edmondac** [comment]
This is related to https://github.com/easybuilders/easybuild-framework/issues/2654 and https://github.com/easybuilders/easybuild-easyconfigs/pull/7110

**Comment by boegel** [comment]
@edmondac Good news: specifying dependencies through a dictionary is actually already supported in the EasyBuild framework... See the `_parse_dependency` method in `easybuild/framework/easyconfig/easyconfig.py`.

It's there but never used in the central repository, mostly because of brevity. But if additional stuff needs to be specified in dependencies, then extending the dict format is way better than extending the tuple format...

The `name`, `version`, `versionsuffix` and `toolchain` keys already work as expected.

For example, this:

```python
dependencies = [('foo', '1.2.3, '-example', ('GCC', '4.8.4')]
```

is equivalent with

```python
dependencies = [{
  'name': 'foo',
  'version': '1.2.3,
  'versionsuffix': '-example',
  'toolchain': {'name': 'GCC', 'version': '4.8.4'},
}]
```

So, adding support for an additional `'arch'` wouldn't be *so* much work, but you may hit some surprises when extending the dict value that is produced by `_parse_dependency`... The best way of figuring it out is by trying it. ;)

**Comment by edmondac** [comment]
Excellent - I'll have a go at that.

**Comment by edmondac** [comment]
Half of the solution is complete in PRs related to CUDA:

-     #2946
-     easybuilders/easybuild-easyblocks#1766
-     easybuilders/easybuild-easyconfigs#8136

Just a solution for Java now required...

**Comment by edmondac** [comment]
This was all done
