### ISSUE TITLE
New --try-toolchain is too strict

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#2662]
We have been using `--try-toolchain` a lot in Compute Canada, and we are always trying to minimize the dependencies, i.e. we don't build with MPI, BLAS, etc. if the software package does not need it. 

This worked great for us until recently. With the new try-toolchain behavior, since upstream does the opposite of us (i.e. compile everything with intel/2018a for example), something like this does not work : 
`eb CDO-1.9.5-intel-2018a.eb --try-toolchain=iompi,2018.3` 

Even though it should work. Nothing in CDO or its dependencies actually requires or uses MKL/BLAS. Yet, I now get the error : 
```
ERROR: No possible mapping from source toolchain spec {'lapack_family': 'IntelMKL', 'name': 'intel', 'blas_family': 'IntelMKL', 'version': '2018a', 'cuda': None, 'comp_family': 'Intel', 'mpi_family': 'IntelMPI'} to target toolchain hierarchy specs [{'lapack_family': None, 'name': 'GCCcore', 'blas_family': None, 'version': '7.3.0', 'cuda': None, 'comp_family': 'GCC', 'mpi_family': None}, {'lapack_family': None, 'name': 'iccifort', 'blas_family': None, 'version': '2018.3', 'cuda': None, 'comp_family': 'Intel', 'mpi_family': None}, {'lapack_family': None, 'name': 'iompi', 'blas_family': None, 'version': '2018.3.312', 'cuda': None, 'comp_family': 'Intel', 'mpi_family': 'OpenMPI'}]
```

**Comment by mboisson** [comment]
Tagging @bartoldeman @ocaisa

**Comment by ocaisa** [comment]
You can revert to previous behaviour with `--force`, see https://github.com/easybuilders/easybuild-framework/pull/2605

**Comment by boegel** [comment]
So, already fixed in EasyBuild v3.7.1 @mboisson?

**Comment by mboisson** [comment]
Looks like we didn't have 3.7.1. Bart will udpate it on our node and I'll report back.

**Comment by mboisson** [comment]
Though I got to admin, `--force` is starting to become used for quite a few varied things. It might be useful to have different options for different forced things ?

**Comment by boegel** [comment]
@mboisson Yeah, you have a good point there... Do you have a particular suggestion in mind?

**Comment by mboisson** [comment]
On a case-by-case basis, maybe. Something like `--try-toolchain-mode=legacy` would have been better than `--force` in this specific example ?

**Comment by boegel** [comment]
That makes sense, something along those lines would indeed have been better... `legacy` is not a good term though, since that gets overloaded easily too. ;)

Having to use `--force` together with `--try-toolchain` can have the side effect over overwriting an existing installation without intending to...

Thoughts @ocaisa?

**Comment by ocaisa** [comment]
We're going deep into corner cases :)
I totally agree that `force` is now being overused, rather than choosing a mode, how about an additional `--try-regex` argument that just triggers the same path?

**Comment by boegel** [comment]
@ocaisa That makes sense too.

@mboisson Isn't it doing that because i) `GCCcore` is a subtoolchain of `iccifort`, and ii) it notices that the original easyconfig was using a toolchain at that "level"?

**Comment by ocaisa** [comment]
@mboisson This logic was deliberate, the idea was that you want to keep simplicity for the end user, if I find an easyconfig for the software I'm interested in another toolchain, I just say `--try-toolchain=...` and it just does "the right thing", mapping it to the same level in the target toolchain. This is simpler than someone having to go searching for what the appropriate level should be or, as in your case, mapping an easyconfig into another compiler family without (certainly in most cases) really meaning to. It's not unlikely that mapping between compiler families will results in a problem.
The issue in your use case is that the trigger for using regex is in a try/except (see https://github.com/easybuilders/easybuild-framework/pull/2605) and since there is a valid mapping available there is no exception. Replacing the use of `--force` with `--try-regex` would solve this since the option becomes explicit rather than implicit.

**Comment by mboisson** [comment]
Ok, I guess we will need to wait for the new feature then.

**Comment by ocaisa** [comment]
If you want a workaround for now, instead of `--force` use `--try-amend=''`, this will also trigger the regex method.

**Comment by mboisson** [comment]
@ocaisa, I have been thinking about the `--try-regex` idea. I think it is a good idea, but with a bad name. It is absolutely not obvious that `--try-regex` would be something you use to replace a toolchain. I would suggest a more explicit name for user-friendliness.  Maybe `--try-toolchain-regex` ?

**Comment by boegel** [comment]
@mboisson How about `--map-toolchains` (enabled by default), so you can revert back to the old behaviour with `--disable-map-toolchains`? See https://github.com/easybuilders/easybuild-framework/pull/2682

**Comment by mboisson** [comment]
Commented in #2682 direclty

**Comment by boegel** [comment]
@mboisson OK to close now #2682 is merged, which adds support for `--disable-map-toolchains` (`--force` now doesn't apply anymore in this context)?

**Comment by mboisson** [comment]
Closing.
