### ISSUE TITLE
bootstrap_eb.py not working under Solus Linux

### ISSUE THREAD

**Issue by sixtyfive** [easybuilders/easybuild-framework#2832]
I'm trying to follow [your installation instructions](https://easybuild.readthedocs.io/en/latest/Installation.html#bootstrapping-procedure), but failing at the very first step. Either with Python 2 (as was probably intended, but is not made clear on that page):

```
$ python2 ./bootstrap_eb.py ~/.local/opt/EasyBuild
[[INFO]] EasyBuild bootstrap script (version 20190322.01, MD5: 6f22322577aa05de75002a5934a2d8d5)
[[INFO]] Found Python 2.7.16 (default, Mar  7 2019, 17:05:26) ; [GCC 8.2.0]

[[INFO]] Installation prefix /home/jrs/.local/opt/EasyBuild
[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: lmod, modulecmd.tcl, modulecmd
Check the output of 'type module' to determine the location of the module command you are using.
```

Or with Python 3 (which would have been good [if it had worked](https://pythonclock.org/)):

```
$ python3 ./bootstrap_eb.py ~/.local/opt/EasyBuild
Traceback (most recent call last):
  File "./bootstrap_eb.py", line 52, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

My distribution is a fully upgraded [Solus](https://getsol.us/home/) (Linux 4.20.16) which doesn't generally have any problems running either Python 2 or Python 3 packages. But then it's neither Debian- nor RedHat-based, so who knows...

**Comment by zao** [comment]
As the error message hints, EasyBuild has some dependencies it requires, which are mentioned in the installation guide you linked. In particular, here you are missing a "modules" tool - either Lmod or Environment Modules.

I took a look at the state of Solus packages and it seems like they don't ship either of those.
In order to build Lmod from source, you need Lua, the Lua packages luaposix and luafilesystem, tcl, and some compiler.

The steps I performed on this distro to install Lmod are:
```bash
eopkg install -c system.devel
eopkg install lua-devel luarocks tcl-devel
luarocks install luafilesystem
luarocks install luaposix
curl -OLJ https://github.com/TACC/Lmod/archive/8.0.4.tar.gz
tar xf Lmod-8.0.4.tar.gz && cd Lmod-8.0.4
CFLAGS=-I/usr/include/tcl8.6 ./configure
CFLAGS=-I/usr/include/tcl8.6 make install
mkdir /etc/profile.d
ln -s /usr/local/lmod/lmod/init/profile /etc/profile.d/lmod.sh
```

With Lmod installed as above and a fresh shell started, the installation procedure succeeds.

```
lars@hodor ~ $ ml
No modules loaded
lars@hodor ~ $ EASYBUILD_PREFIX=$HOME/.local/easybuild
lars@hodor ~ $ python bootstrap_eb.py $EASYBUILD_PREFIX
[[INFO]] EasyBuild bootstrap script (version 20190322.01, MD5: 6f22322577aa05de75002a5934a2d8d5)
[[INFO]] Found Python 2.7.16 (default, Mar  7 2019, 17:05:26) ; [GCC 8.2.0]

[[INFO]] Installation prefix /home/lars/.local/easybuild
[[INFO]] Found module command '/usr/local/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] Suitable setuptools installation already found, skipping stage 0...


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmp7X9y5c/eb_stage1 easybuild'
[[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmp7X9y5c/eb_stage1 vsc-base'


[[INFO]] +++ STAGE 2: installing EasyBuild in /home/lars/.local/easybuild with EasyBuild from stage 1...

== temporary log file in case of crash /tmp/eb-u2pxYh/easybuild-v1hCgS.log
== processing EasyBuild easyconfig /tmp/tmp7X9y5c/EasyBuild-3.9.0.eb
== building and installing EasyBuild/3.9.0...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /home/lars/.local/easybuild/software/EasyBuild/3.9.0/easybuild/easybuild-EasyBuild-3.9.0-20190414.190858.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-u2pxYh/easybuild-v1hCgS.log* have been removed.
== Temporary directory /tmp/eb-u2pxYh has been removed.
[[INFO]] EasyBuild module installed: /home/lars/.local/easybuild/modules/all/EasyBuild/3.9.0.lua

[[INFO]] Bootstrapping EasyBuild completed!

[[INFO]] EasyBuild v3.9.0 was installed to /home/lars/.local/easybuild, so make sure your $MODULEPATH includes /home/lars/.local/easybuild/modules/all

[[INFO]] Run 'module load EasyBuild', and run 'eb --help' to get help on using EasyBuild.
[[INFO]] Set $EASYBUILD_MODULES_TOOL to 'Lmod' to use the same modules tool as was used now.

[[INFO]] By default, EasyBuild will install software to $HOME/.local/easybuild.
[[INFO]] To install software with EasyBuild to /home/lars/.local/easybuild, make sure $EASYBUILD_INSTALLPATH is set accordingly.
[[INFO]] See http://easybuild.readthedocs.org/en/latest/Configuration.html for details on configuring EasyBuild.
lars@hodor ~ $ ml use $EASYBUILD_PREFIX/modules/all
lars@hodor ~ $ ml av

---------------------------------------------------------- /home/lars/.local/easybuild/modules/all ----------------------------------------------------------
   EasyBuild/3.9.0

----------------------------------------------------------- /usr/local/lmod/lmod/modulefiles/Core -----------------------------------------------------------
   lmod    settarg

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".


lars@hodor ~ $ ml EasyBuild
lars@hodor ~ $ eb --version
This is EasyBuild 3.9.0 (framework: 3.9.0, easyblocks: 3.9.0) on host hodor.
lars@hodor ~ $
```

EasyBuild may have some additional requirements depending on what you're going to build, like OpenSSL and ibverbs.

**Comment by boegel** [comment]
@sixtyfive W.r.t. Python 3 support: we're very much aware of that, and are actively working on fixing the support for running EasyBuild on top of Python 3.
The next major release of EasyBuild (4.0) will support running on top of Python 3.x (see https://github.com/easybuilders/easybuild-framework/issues?q=label%3Apython3+is%3Aclosed, in particular https://github.com/easybuilders/easybuild-framework/issues/133). 

The bootstrap script is supposed to work when run with Python 3.x, as long as `python2` is around as well (since EasyBuild 3.x still requires Python 2 for now).
It seems like that was broken without us noticing it, I'll look into fixing that (and making sure we check for it).

W.r.t. the problem you are seeing: EasyBuild requires a modules tool to be available as @zao already pointed out, see also https://easybuild.readthedocs.io/en/latest/Installation.html#requirements and https://easybuild.readthedocs.io/en/latest/Installation.html#required-modules-tool .
If you have none installed yet, I'd highly recommend looking into Lmod, see also https://easybuild.readthedocs.io/en/latest/Installing-Lmod-without-root-permissions.html

**Comment by sixtyfive** [comment]
Finally I've gotten around to trying @zao's instructions and it worked that way, thank you! FWIW I don't think I would have been able to figure it out on my own, so it's good that this thread is now discoverable by search engines.

Since EasyBuild seems to meet Solus's [Package Inclusion Policy](https://getsol.us/articles/packaging/package-inclusion-policy/en/), I've opened a [request to include it](https://dev.getsol.us/T7939).

**Comment by boegel** [comment]
@sixtyfive In that case, can we close this issue?

**Comment by sixtyfive** [comment]
Oh, yes, sure, sorry! :-P
