### ISSUE TITLE
easybuild 3.9.0 dependency 

### ISSUE THREAD

**Issue by fizwit** [easybuilders/easybuild-framework#2879]
easybuild 3.9.0 is using the wrong toolchain for module lookups when gompi is in part of the dependancy list. 3.9.0 is searching for gompi version of netCDF and HDF5, when foss-2019a modules are available.  I was able to build GDAL with EB 3.8.1, but failed with 3.9.0.  See pr #8310 for GDAL-2.4.1 easyconfig.

eb GDAL-2.4.1-foss-2019a-Python-3.7.3.eb
== temporary log file in case of crash /tmp/eb-eFaCI5/easybuild-R52GCw.log
== processing EasyBuild easyconfig /ls2/GDAL-2.4.1-foss-2019a-Python-3.7.3.eb
== building and installing GDAL/2.4.1-foss-2019a-Python-3.7.2...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /app/build/GDAL/2.4.1/foss-2019a-Python-3.7.2): build failed (first 300 chars): Missing modules for dependencies (use --robot?): HDF5/1.10.5-gompi-2019a, netCDF/4.6.2-gompi-2019a

**Comment by akesandgren** [comment]
No, you just have to do what is says: use --robot
I.e. you need to let easybuild build the whole chain of dependencies.

**Comment by fizwit** [comment]
HDF5/1.10.5-foss-2019a was available, but 3.9.0 did not find it.  Using robot would result in having a bunch of non-standard packages. The same GDAL easyconfig built without issue after downgrading to 3.8.1.

**Comment by akesandgren** [comment]
Do you mean that HDF5/1.10.5-foss-2019a  was already built and you wanted it to use that version explicitly?
Do you have minimal-toolchains true or false?
If it is True then easybuild searches from the lowest toolchain (GCCcore) and up to find a valid easyconfig file. If False it searches top-to-bottom, ie starting at foss in this case since GDAL was at foss.

If you have --use-existing-modules true then, if i remember correctly, it would have found your existing HDF5 at foss level even with minimal-toolchains true.

So behaviour depends on your settings.

**Comment by fizwit** [comment]
use-existing-modules = false
minimal-toolchains = false

**Comment by akesandgren** [comment]
I forgot to say that with use-existing-modules=false it searches for a easyconfig file, and uses the one it finds. So which easyconfig files do you have available for HDF5 in your robot-paths?

**Comment by fizwit** [comment]
the issue is resolved by using the use-existing-modules flag AND/OR defining robot path correctly.  I presume the difference is a file search for the easyconfig file vs. using lmod to search for a module. I do not have a local robot-path configured and our easyconfigs are kept in file tree [ h: [h5py,  HarfBuzz,  hdf5,  HDF5, ...], i: [ICU, IGV, ...]]
