### ISSUE TITLE
rpath compiler wrapper not found in some corner cases

### ISSUE THREAD

**Issue by pescobar** [easybuilders/easybuild-framework#2964]
I have found a makefile that doesn't work when using the RPATH option in easybuild because it cannot find the compiler wrapper generated by easybuild.

I was getting this error in the build log:
```
/bin/sh: /scratch/eb-4AOIkw/tmpoGHcBP/rpath_wrappers/gcc_wrapper/g++: No such file or directory
make: *** [centrifuge-build-bin] Error 127
```

but the `g++` wrapper generated by easybuild was located in a different folder `/scratch/eb-k3q0FV/tmpxxdCS_/rpath_wrappers/gxx_wrapper`

the problem was that the makefile had these lines to find the `g++` path
```
GCC_PREFIX = $(shell dirname `which gcc`)
GCC_SUFFIX =
CC = $(GCC_PREFIX)/gcc$(GCC_SUFFIX)
CPP = $(GCC_PREFIX)/g++$(GCC_SUFFIX)
```

the workaround I applied was to use `buildopts = 'CC="$CC" CPP="$CXX" '` in the easyconfig but if both rpath wrappers for `gcc` and `g++` were located in the same folder we would not hit this problem

**Comment by boegel** [comment]
While checking the code, it turns out there *is* a reason why we put each wrapper in its own directory.

The directory in which the wrapper is located is used in the RPATH wrapper itself to filter its own location from `$PATH` (to avoid the wrapper calling itself), as follows:

```shell
# exclude location of this wrapper from $PATH to avoid other potential wrappers calling this wrapper
export PATH=$(echo $PATH | tr ':' '\n' | grep -v "^%(wrapper_dir)s$" | tr '\n' ':')
```

I'm not 100% sure what the impact on that would be of putting all wrappers in the same directory...
If that's done, the `$PATH` filtering will result in all wrappers being thrown out of `$PATH`, which would cause some supposed-to-be-wrapped commands to be run without the RPATH wrapper (for example when `gcc` calls out to `ld`).

So, it seems like we should leave things as is, and just fix software that assumes that all compiler commands are in the same location?

**Comment by pescobar** [comment]
I agree this is a very specific corner case and IMO it's not worth modifying easybuild to workaround . I opened this issue mainly because you asked me to do it to keep track of this issue ;) 

btw I also hitted the issue of the recursive rpath wrapper calling itself again and again and it's much worse :)
