### ISSUE TITLE
"Fake" vsc not hit when importing vsc in develop

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-framework#2991]
When working on the current develop branch [1], if `from vsc.utils import fancylogger` is present in a module naming scheme file the log is redirected to stdout even if the `-l` option is not used. Removing the output of `vsc.__file__` also does not solve the problem.

[1] Last commit: https://github.com/easybuilders/easybuild-framework/commit/ec3c0cdf594a8bc561bf25d9f3c0bdad05c4e3ed

**Comment by boegel** [comment]
The problem here is that the fake `vsc` namespace that is installed via `install_fake_vsc` is installed too late, after parsing the configuration options (which involves importing included Python modules like custom module module naming scheme).

`install_fake_vsc` should be moved to the top of `set_up_configuration`, but we'll also need to avoid using the `mkdir` and `write_file` functions in `install_fake_vsc`, since those expect that the build options are already in place (which they only can be after parsing the configuration).

**Comment by boegel** [comment]
fixed in #2993, thanks for reporting this @vanzod!
