### ISSUE TITLE
Bootstrap script incompatible with python3

### ISSUE THREAD

**Issue by bartoldeman** [easybuilders/easybuild-framework#3027]
As observed in #3017 `bootstrap_eb.py` is not compatible with Python3. It relies on `/usr/bin/env python` being Python 2 (which is still the case on most but not all Linux distributions).

Fixing that is not a simple case of translating the file, as it included a base64'ed gzipped setuptools helper that is outdated.

One way that seems to work for stage1 is something akin too:
```
wget https://bootstrap.pypa.io/get-pip.py
export EB_TMPLOC=<sometmplocation like /tmp/tmpRG7iSQ/eb_stage1>
export PYTHONPATH=$EB_TMPLOC
python3 get-pip.py --prefix=$EB_TMPLOC
$EB_TMPLOC/bin/pip --prefix=$EB_TMPLOC easybuild
```
after that it can do stage2 as usual, since `eb` is installed now.

I'm just floating this as an idea since it's a complete redesign of the stage1 of the bootstrap.

**Comment by boegel** [comment]
I started working on this, and it's indeed a bit more work that just porting the script itself.

The good thing is that since EasyBuild 4.0 no longer requires `setuptools` at all, we can actually move get rid of the base64'd `distribute` installation script (and just check if `setuptools` is available in case somebody installs an older version of EasyBuild, rather than trying to install it ourselves which is a bit of a desperate attempt anyway).

That also means no longer using `easy_install` during stage 1 (which is provided by `setuptools`), we should just use `setup.py install` (which implies downloading and unpacking the source tarballs first).

Kickstarted the effort in #3028...
