### ISSUE TITLE
using --include-easyblocks-from-pr together with a local easyconfig file fails

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3283]
Example:

```
$ ls ABAQUS-2019.eb
ABAQUS-2019.eb

$ eb ABAQUS-2019.eb --installpath /tmp/$USER --include-easyblocks-from-pr 2034
...
ERROR: Can't find path /tmp/eb-d2fKqd/tmpA9Jiv_/easybuilders/ABAQUS-2019.eb
```

Using absolute path to easyconfig instead via `eb $PWD/AABQUS-2019.eb ...` does work...

**Comment by migueldiascosta** [comment]
It seems this is actually not *only* related to `--include-easyblocks-from-pr`...

For instance, if you mix that local file with files from `--from-pr`, you get the same behaviour, but it seems it never came up before (?) because that's a weird scenario

The workaround is either to use the absolute path as @boegel mentioned, or to add the folder where the local easyconfig is to the robot path, e.g. in this case with `-r .`

Now, the reason this happens is that the `extract_file` method, called from `download_repo`, changes the working directory (see also https://github.com/easybuilders/easybuild-framework/issues/2858), and in fact everything that comes after `download_repo` seems to rely on that...

**Comment by boegel** [comment]
@migueldiascosta I'm changing `download_repo` so it doesn't have the side effect of changing directories anymore in #3486 

As far as I can tell, nothing that calls `download_repo` relies on the changing of directories at all?
The explicit `change_dir` is just a change we made as a part of #3292 when we changed `extract_file`...
