### ISSUE TITLE
Easybuild 4.3.4 bootstrap fails because of vsc-install

### ISSUE THREAD

**Issue by antoant1** [easybuilders/easybuild-framework#3690]
Hello,

I have an installation of CentOS 7.8 and I am trying to install EasyBuild but it seems that easy_install cannot find vsc-install
My problem is similar to issue #3056 but the solution of it is not applicable in my case since I do have setuptools installed.

```
$ python bootstrap_eb.py $EASYBUILD_PREFIX

[[INFO]] EasyBuild bootstrap script (version 20210106.01, MD5: 2e9a1c86bea34d12b2fab3a8e79932fd)
[[INFO]] Found Python 2.7.5 (default, Apr  2 2020, 13:16:51) ; [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

[[INFO]] Installation prefix /home/user/eb
[[INFO]] Found module command '/usr/share/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] Suitable setuptools installation already found, skipping stage 0...


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] running pre-install command 'easy_install --quiet --upgrade --prefix=/tmp/tmp9wgXht/eb_stage1 vsc-install<0.11.4'
[[ERROR]] Running 'easy_install --quiet --upgrade --prefix=/tmp/tmp9wgXht/eb_stage1 vsc-install<0.11.4' failed: error: Could not find suitable distribution for Requirement.parse('vsc-install<0.11.4')
Traceback (most recent call last):
  File "bootstrap_eb.py", line 380, in run_easy_install
    easy_install.main(args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1992, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1979, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1996, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 169, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: Could not find suitable distribution for Requirement.parse('vsc-install<0.11.4')
```
It seems like easy_install is not able to talk to pypi

**Comment by boegel** [comment]
@antoant1 Which setuptools version do you have here? It's probably too old to talk to PyPI...

I strongly recommend you to use the 3-step installation procedure outlined in https://easybuilders.github.io/easybuild-tutorial/2021-lust/installation/#method-2-installing-easybuild-with-easybuild that is essentially equivalent to using the bootstrap script, which was the best way to install EasyBuild from scratch, but isn't anymore (we really need to get around to updating the documentation at https://docs.easybuild.io/en/latest/Installation.html to make that clear).

I also strongly recommend to use `python3` rather than `python` (which is Python 2 on CentOS 7), if at all possible.

Do let us know how it works out, or if you need any help.

**Comment by antoant1** [comment]
@boegel We have version 1.19.11 which is the default that comes with CentOS 7.8 and which worked about 6 months ago when I tried it last.

I have used python3 and the bootstrap script to install this time.
I will try the pip method next time I need to install EB on a new machine.
As you have said it would be nice if the installation section of the documentation was updated.
