### ISSUE TITLE
Remove bootstrap script

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3789]
I'd suggest to remove the bootstrap script. The updated installation instructions for installing EB via pip are enough and if not ensurepip can be used to even install pip.
If we really want to keep it to easily install an EB module file then we should basically fully rewrite it:
- Install pip via ensurepip if not present
- Install EB via pip
- Install EB via EB

This will be VERY much simpler than the current one and easier to maintain. The hacks and workarounds for Python 2.6 etc are no longer required.

Remove the script would also allow to remove the tests on CI (half the tests [23] test the bootstrap script)

**Comment by boegel** [comment]
I think we shouldn't do this before we have EasyBuild 5.0, and even then we should replace the script by a trivial one that just produces a message to the installation docs (but that doesn't need testing, of course).

**Comment by Flamefire** [comment]
The bootstrap script in its current state doesn't exactly work well. It has quite a few corner conditions where it will fail, see the open issues and PRs
Then how about the proposed simplification? All supported Python versions have the ensurepip module IIRC, so the whole script can be condensed to about 30-40 lines :)

**Comment by boegel** [comment]
The bootstrap script is deprecated (see #3742), so I'm personally not included to spend more time on it.

It produces a big fat clear warning, and allows you to opt-in to trying it. If it works, fine. If not, you should explore the recommended installation procedure.

For the time being, I'm fine with leaving it in that state. Totally removing it may lead to confusion (since I can imagine lots of people are used to installing it that way). Making it non-functional seems overkill at this point.

If you'd like to try and come up with a better one from scratch, I won't stop you, but I also don't want to start promoting it again...

**Comment by boegel** [comment]
bootstrap script was removed in #4233, so closing this...
