### ISSUE TITLE
easybuild and module versions

### ISSUE THREAD

**Issue by smichnowicz** [easybuilders/easybuild-framework#3815]
Dear Group
I am exploring the use of easybuild on a newly built test Ubuntu 20.04 node. When I went **eb GCC** I get an error
**ERROR: Failed to determine Environment Modules v3 version from option '--version' output: Modules Release 4.4.1 (2020-01-03)**
and I found that **module --version** produces different formatted outputs between two different versions on two different OSs. Ubuntu had version 4.4.1 and a Centos box had version 3.2.10.  The easybuild code consists of:

> NAME = "Environment Modules v3"
>     COMMAND = "modulecmd"
>     REQ_VERSION = '3.2.10'
>     MAX_VERSION = '3.99'
>     VERSION_REGEXP = r'^\s*(VERSION\s*=\s*)?(?P<version>\d\S*)\s*'

So does mean Easybuild can't be used with this version of **modules** (4.4.1)? If it can, can you advise me how to configure it so that it will work on Ubunutu.
thanks Simon

**Comment by boegel** [comment]
This problem should be fixed with the (trivial) changes in https://github.com/easybuilders/easybuild-framework/pull/3816, which will be included in the upcoming EasyBuild v4.4.2 release.

If you want to, you can make the single-line change shown in https://github.com/easybuilders/easybuild-framework/pull/3816/files in an existing EasyBuild release as well, it should be enough to let EasyBuild use a recent version of Environment Modules 4.x regardless of where `modulecmd.tcl` is located exactly in the installation.
