### ISSUE TITLE
Setting checksums to `[None]` logs an error and continues

### ISSUE THREAD

**Issue by PetrKralCZ** [easybuilders/easybuild-framework#4260]
When using
```python
checksums = [None]
```
Easybuild logs an error
```
ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Couldn't find file checksums.json anywhere, and downloading it is disabled
```
but the build process continues and eventually finishes successfully.

**Comment by boegel** [comment]
This is caused by the `try`/`except` setup here: https://github.com/easybuilders/easybuild-framework/blob/b1a528735d8e30769b8e512042d7d5cc10406574/easybuild/framework/easyblock.py#L398-L405

`obtain_file` raises an error if the file can't be found, which is caught there

We should instead somehow specify that `obtain_file` should try to find the file, and just log a warning if it's not found, and returns `None`.

@PetrKralCZ Are you up for taking a look at that yourself?
