### ISSUE TITLE
PR title created with --new-pr misses 2nd toolchain

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#4446]
I just did `eb --new-pr molmod-1.4.8-foss-2022a.eb molmod-1.4.8-gfbf-2022b.eb TAMkin-1.2.6-foss-2022a.eb TAMkin-1.2.6-foss-2022b.eb` which created https://github.com/easybuilders/easybuild-easyconfigs/pull/19723 with the title

> {chem,math}[foss/2022a] molmod v1.4.8, TAMkin v1.2.6

I.e. it misses the 2022b toolchain!

However when using only a single software it works:   
`eb --new-pr TAMkin-1.2.6-foss-2020a-Python-3.8.2.eb TAMkin-1.2.6-foss-2020b.eb TAMkin-1.2.6-foss-2021a.eb TAMkin-1.2.6-foss-2021b.eb`

> {chem}[foss/2020a,foss/2020b,foss/2021a,foss/2021b] TAMkin v1.2.6 w/ Python 3.8.2

**Comment by Micket** [comment]
This isn't so much a bug report though, it's just very intentional by the det_pr_title function to only include the most popular toolchain in an effort to keep them short.
https://github.com/easybuilders/easybuild-framework/blob/92d29680fb5d14086943c96a9efcd2558093f6ae/easybuild/tools/github.py#L1589

The second example "works" because foss/2020a,foss/2020b,foss/2021a,foss/2021b were equally common.

**Comment by Flamefire** [comment]
I see, OK then.
